<?php

namespace Database\Factories;

use App\Enums\Party;
use App\Enums\SessionStatus;
use App\Models\ClassSession;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<ClassSession>
 */
class ClassSessionFactory extends Factory
{
    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'instructor_id' => User::factory()->instructor(),
            'student_id' => User::factory()->student(),
            'scheduled_date' => now()->toDateString(),
            'scheduled_time' => '18:30:00',
            'held_date' => null,
            'status' => null,
        ];
    }

    public function present(): static
    {
        return $this->state(fn () => [
            'status' => SessionStatus::Present,
            'absent_by' => null,
        ]);
    }

    /** Student's fault — still pays the instructor. */
    public function studentAbsent(): static
    {
        return $this->state(fn () => [
            'status' => SessionStatus::Absent,
            'absent_by' => Party::Student,
        ]);
    }

    /** Instructor's fault — deducted from their payout. */
    public function teacherAbsent(): static
    {
        return $this->state(fn () => [
            'status' => SessionStatus::Absent,
            'absent_by' => Party::Teacher,
        ]);
    }

    public function postponed(): static
    {
        return $this->state(fn () => [
            'status' => SessionStatus::Postponed,
            'postponed_by' => Party::Student,
        ]);
    }

    /**
     * Taught on $heldDate but occupying the $scheduledDate slot.
     * paid_date is generated by the database as COALESCE(held_date, scheduled_date).
     */
    public function early(string $heldDate, string $scheduledDate): static
    {
        return $this->state(fn () => [
            'held_date' => $heldDate,
            'scheduled_date' => $scheduledDate,
            'status' => SessionStatus::Present,
        ]);
    }

    public function on(string $date): static
    {
        return $this->state(fn () => ['scheduled_date' => $date]);
    }
}
