<?php

namespace Tests\Feature;

use App\Enums\PayoutStatus;
use App\Enums\TeachingMethod;
use App\Models\ClassSession;
use App\Models\Payout;
use App\Models\SessionReport;
use App\Models\StudentProfile;
use App\Models\User;
use App\Services\Earnings\PayoutService;
use App\Support\PayoutWindow;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Validation\ValidationException;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * Freezing a week's earnings into a payslip.
 *
 * This closes a real gap: the legacy `payouts` table existed but nothing ever
 * wrote to it, so editing an old attendance record silently restated what had
 * already been paid.
 */
class PayoutServiceTest extends TestCase
{
    use RefreshDatabase;

    private PayoutService $payouts;

    private User $admin;

    private User $instructor;

    private const WEEK_START = '2025-08-02';

    protected function setUp(): void
    {
        parent::setUp();

        $this->payouts = app(PayoutService::class);
        $this->admin = User::factory()->admin()->create();
        $this->instructor = User::factory()->instructor()->create();

        config()->set('academy.feedback_required_from', '2024-01-01');
        config()->set('academy.feedback_exempt_instructor_ids', []);
    }

    private function window(): PayoutWindow
    {
        return PayoutWindow::forDate(self::WEEK_START);
    }

    /**
     * A paid, reported session worth a known amount.
     */
    private function paidSession(string $date, TeachingMethod $method = TeachingMethod::Audio, int $minutes = 25): void
    {
        $student = User::factory()->student()->create();

        StudentProfile::factory()->method($method, $minutes)->create([
            'user_id' => $student->id,
            'instructor_id' => $this->instructor->id,
        ]);

        $session = ClassSession::factory()->present()->create([
            'instructor_id' => $this->instructor->id,
            'student_id' => $student->id,
            'scheduled_date' => $date,
        ]);

        SessionReport::factory()->forSession($session)->create();
    }

    #[Test]
    public function it_freezes_the_weeks_figures(): void
    {
        $this->paidSession('2025-08-04', TeachingMethod::VideoKids, 25);  // 91.67
        $this->paidSession('2025-08-05', TeachingMethod::Audio, 25);      // 79.17

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());

        $this->assertSame('170.84', $payout->gross_earnings);
        $this->assertSame('0.00', $payout->deductions);
        // net_earnings is generated by the database from gross - deductions.
        $this->assertSame('170.84', $payout->net_earnings);
        $this->assertSame(2, $payout->sessions_paid);
        $this->assertSame(PayoutStatus::Pending, $payout->status);
        $this->assertSame(self::WEEK_START, $payout->week_start->toDateString());
        $this->assertSame('2025-08-08', $payout->week_end->toDateString());
    }

    #[Test]
    public function it_records_the_split_by_teaching_method(): void
    {
        $this->paidSession('2025-08-04', TeachingMethod::Audio, 25);
        $this->paidSession('2025-08-05', TeachingMethod::VideoKids, 25);
        $this->paidSession('2025-08-06', TeachingMethod::VideoAdults, 25);

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());

        $this->assertSame('79.17', $payout->audio_earnings);
        $this->assertSame('91.67', $payout->video_kids_earnings);
        $this->assertSame('87.50', $payout->video_adults_earnings);
    }

    #[Test]
    public function it_records_deductions_which_the_legacy_table_could_not(): void
    {
        $this->paidSession('2025-08-04', TeachingMethod::Audio, 25);

        $student = User::factory()->student()->create();
        StudentProfile::factory()->method(TeachingMethod::Audio, 25)->create([
            'user_id' => $student->id,
            'instructor_id' => $this->instructor->id,
        ]);
        ClassSession::factory()->teacherAbsent()->create([
            'instructor_id' => $this->instructor->id,
            'student_id' => $student->id,
            'scheduled_date' => '2025-08-05',
        ]);

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());

        $this->assertSame('79.17', $payout->gross_earnings);
        $this->assertSame('79.17', $payout->deductions);
        $this->assertSame('0.00', $payout->net_earnings);
        $this->assertSame(1, $payout->sessions_deducted);
    }

    #[Test]
    public function finalising_twice_updates_rather_than_duplicating(): void
    {
        $this->paidSession('2025-08-04');

        $first = $this->payouts->finalise($this->admin, $this->instructor, $this->window());

        // More work turns up for the same week.
        $this->paidSession('2025-08-05');

        $second = $this->payouts->finalise($this->admin, $this->instructor, $this->window());

        $this->assertSame($first->id, $second->id, 'one payslip per instructor per week');
        $this->assertSame('158.34', $second->gross_earnings);
        $this->assertSame(1, $this->instructor->payouts()->count());
    }

    #[Test]
    public function a_paid_week_is_not_silently_restated(): void
    {
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $this->payouts->markPaid($this->admin, $payout);

        // Attendance is edited after payment.
        $this->paidSession('2025-08-05');

        $this->expectException(ValidationException::class);
        $this->payouts->finalise($this->admin, $this->instructor, $this->window());
    }

    #[Test]
    public function a_paid_week_can_be_restated_deliberately(): void
    {
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $this->payouts->markPaid($this->admin, $payout);

        $this->paidSession('2025-08-05');

        $restated = $this->payouts->finalise($this->admin, $this->instructor, $this->window(), force: true);

        $this->assertSame('158.34', $restated->gross_earnings);
    }

    #[Test]
    public function marking_paid_records_who_and_when(): void
    {
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $paid = $this->payouts->markPaid($this->admin, $payout, 'Bank transfer');

        $this->assertSame(PayoutStatus::Paid, $paid->status);
        $this->assertNotNull($paid->paid_at);
        $this->assertSame($this->admin->id, $paid->paid_by);
        $this->assertSame('Bank transfer', $paid->notes);
    }

    #[Test]
    public function paying_twice_is_refused(): void
    {
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $this->payouts->markPaid($this->admin, $payout);

        $this->expectException(ValidationException::class);
        $this->payouts->markPaid($this->admin, $payout->refresh());
    }

    #[Test]
    public function finalising_the_week_skips_instructors_who_earned_nothing(): void
    {
        $this->paidSession('2025-08-04');

        // Two more instructors with no sessions at all.
        User::factory()->instructor()->count(2)->create();

        $result = $this->payouts->finaliseWeek($this->admin, $this->window());

        $this->assertSame(1, $result['finalised']);
        $this->assertSame(2, $result['skipped']);
        $this->assertSame(1, Payout::count());
    }

    #[Test]
    public function a_frozen_payslip_is_unaffected_by_later_attendance_edits(): void
    {
        // The whole point of freezing.
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $this->payouts->markPaid($this->admin, $payout);

        $frozen = $payout->refresh()->net_earnings;

        // Wipe the attendance the payslip was based on.
        ClassSession::query()->delete();

        $this->assertSame(
            $frozen,
            $payout->refresh()->net_earnings,
            'a paid payslip must not change when attendance does'
        );
    }

    #[Test]
    public function it_writes_an_audit_entry(): void
    {
        $this->paidSession('2025-08-04');

        $payout = $this->payouts->finalise($this->admin, $this->instructor, $this->window());
        $this->payouts->markPaid($this->admin, $payout);

        $this->assertDatabaseHas('audit_logs', [
            'action' => 'payout.finalised',
            'user_id' => $this->admin->id,
        ]);
        $this->assertDatabaseHas('audit_logs', [
            'action' => 'payout.paid',
            'user_id' => $this->admin->id,
        ]);
    }
}
