<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A finalised weekly payslip: the earnings report frozen at the moment of
 * payment, so later edits to attendance cannot silently restate what was paid.
 *
 * Legacy `payouts` stored only gross figures split by teaching method, with no
 * record of deductions — yet teacher-absent sessions ARE deducted, and the
 * instructor earnings page displayed that subtraction without ever persisting
 * it. Gross, deductions and net are now all stored, and net is generated by the
 * database so the three can never disagree.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payouts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('instructor_id')->constrained('users')->cascadeOnDelete();

            // Payout week, Saturday -> Friday inclusive (config/academy.php).
            // Dates, not datetimes: the window is whole days in KST, and the
            // legacy DATETIME columns invited timezone drift at the boundary.
            $table->date('week_start');
            $table->date('week_end');

            $table->decimal('gross_earnings', 10, 2)->default(0);
            $table->decimal('deductions', 10, 2)->default(0);
            $table->decimal('net_earnings', 10, 2)->storedAs('gross_earnings - deductions');

            // Gross split by teaching method, for reconciliation.
            $table->decimal('audio_earnings', 10, 2)->default(0);
            $table->decimal('video_kids_earnings', 10, 2)->default(0);
            $table->decimal('video_adults_earnings', 10, 2)->default(0);

            $table->unsignedSmallInteger('sessions_paid')->default(0);
            $table->unsignedSmallInteger('sessions_deducted')->default(0);

            $table->enum('status', ['pending', 'paid'])->default('pending');
            $table->timestamp('paid_at')->nullable();
            $table->foreignId('paid_by')->nullable()->constrained('users')->nullOnDelete();
            $table->text('notes')->nullable();

            $table->timestamps();

            // One payslip per instructor per week.
            $table->unique(['instructor_id', 'week_start'], 'payouts_instructor_week_unique');
            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payouts');
    }
};
