<?php

namespace App\Models;

use App\Enums\Party;
use App\Enums\SessionStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * One class slot between an instructor and a student.
 *
 * `scheduled_date` is the slot in the student's timetable. `held_date` is set
 * only when the class was taught early, on a different day from its slot.
 * `paid_date` is a database-generated COALESCE of the two and is what every
 * payout calculation keys off — see the create migration for why.
 */
class ClassSession extends Model
{
    use HasFactory;

    protected $fillable = [
        'instructor_id',
        'student_id',
        'scheduled_date',
        'scheduled_time',
        'held_date',
        'status',
        'absent_by',
        'postponed_by',
        'postpone_reason',
        'makeup_time',
        'rescheduled_date',
        'rescheduled_time',
        'marked_by',
        'marked_at',
    ];

    /**
     * paid_date is generated by the database; never let it be written.
     */
    protected $guarded = ['id', 'paid_date'];

    protected $casts = [
        'scheduled_date' => 'date',
        'held_date' => 'date',
        'paid_date' => 'date',
        'rescheduled_date' => 'date',
        'status' => SessionStatus::class,
        'absent_by' => Party::class,
        'postponed_by' => Party::class,
        'marked_at' => 'datetime',
    ];

    // ---------------------------------------------------------------- relations

    public function instructor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'instructor_id');
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(User::class, 'student_id');
    }

    public function markedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'marked_by');
    }

    public function report(): HasOne
    {
        return $this->hasOne(SessionReport::class);
    }

    // ------------------------------------------------------------------- scopes

    /** Settled sessions — present or absent. Excludes postponed and unmarked. */
    public function scopeSettled(Builder $query): Builder
    {
        return $query->whereIn('status', SessionStatus::payableValues());
    }

    public function scopeStatus(Builder $query, SessionStatus $status): Builder
    {
        return $query->where('status', $status);
    }

    public function scopeAbsentBy(Builder $query, Party $party): Builder
    {
        return $query->where('status', SessionStatus::Absent)->where('absent_by', $party);
    }

    /** Sessions whose PAID date falls in the window (inclusive). */
    public function scopePaidBetween(Builder $query, string $start, string $end): Builder
    {
        return $query->whereBetween('paid_date', [$start, $end]);
    }

    public function scopeForInstructor(Builder $query, int $instructorId): Builder
    {
        return $query->where('instructor_id', $instructorId);
    }

    /** Classes taught ahead of their scheduled slot. */
    public function scopeEarly(Builder $query): Builder
    {
        return $query->whereNotNull('held_date');
    }

    public function scopeUnmarked(Builder $query): Builder
    {
        return $query->whereNull('status');
    }

    // ------------------------------------------------------------------ helpers

    public function isEarly(): bool
    {
        return $this->held_date !== null;
    }

    public function isSettled(): bool
    {
        return in_array($this->status?->value, SessionStatus::payableValues(), true);
    }

    /**
     * Whether this session pays the instructor.
     *
     * Present pays. Student-absent pays — the instructor showed up and waited.
     * Teacher-absent does not; it is deducted instead. Postponed and unmarked
     * sessions were never taught.
     */
    public function isPayable(): bool
    {
        return $this->status === SessionStatus::Present
            || ($this->status === SessionStatus::Absent && $this->absent_by === Party::Student);
    }

    /** Whether this session is deducted from the instructor's payout. */
    public function isDeductible(): bool
    {
        return $this->status === SessionStatus::Absent && $this->absent_by === Party::Teacher;
    }
}
