<?php

namespace App\Models;

use App\Enums\Party;
use App\Enums\SessionStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * One class slot between an instructor and a student.
 *
 * `scheduled_date` is the slot in the student's timetable. `held_date` is set
 * only when the class was taught early, on a different day from its slot.
 * `paid_date` is a database-generated COALESCE of the two and is what every
 * payout calculation keys off — see the create migration for why.
 */
class ClassSession extends Model
{
    use HasFactory;

    /**
     * How the legacy app recorded a makeup, and still how nearly every makeup in
     * the database is stored.
     *
     * Legacy wrote a SECOND row, on the makeup date, unmarked, with the agreed
     * hour in `makeup_time` and this prefix plus the original date in
     * `postpone_reason` (app/views/instructor/classes.php). The rewrite records
     * the same fact the other way round — `rescheduled_date` on the postponed
     * row, no second row — but the import copied the legacy rows across
     * untouched, so both shapes are live and anything reading makeups has to
     * understand each of them.
     */
    private const MAKEUP_MARKER = 'Rescheduled from ';

    protected $fillable = [
        'instructor_id',
        'student_id',
        'scheduled_date',
        'scheduled_time',
        'held_date',
        'status',
        'absent_by',
        'postponed_by',
        'postpone_reason',
        'makeup_time',
        'rescheduled_date',
        'rescheduled_time',
        'marked_by',
        'marked_at',
    ];

    /**
     * paid_date is generated by the database; never let it be written.
     */
    protected $guarded = ['id', 'paid_date'];

    protected $casts = [
        'scheduled_date' => 'date',
        'held_date' => 'date',
        'paid_date' => 'date',
        'rescheduled_date' => 'date',
        'status' => SessionStatus::class,
        'absent_by' => Party::class,
        'postponed_by' => Party::class,
        'marked_at' => 'datetime',
    ];

    // ---------------------------------------------------------------- relations

    public function instructor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'instructor_id');
    }

    public function student(): BelongsTo
    {
        return $this->belongsTo(User::class, 'student_id');
    }

    public function markedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'marked_by');
    }

    public function report(): HasOne
    {
        return $this->hasOne(SessionReport::class);
    }

    // ------------------------------------------------------------------- scopes

    /** Settled sessions — present or absent. Excludes postponed and unmarked. */
    public function scopeSettled(Builder $query): Builder
    {
        return $query->whereIn('status', SessionStatus::payableValues());
    }

    public function scopeStatus(Builder $query, SessionStatus $status): Builder
    {
        return $query->where('status', $status);
    }

    public function scopeAbsentBy(Builder $query, Party $party): Builder
    {
        return $query->where('status', SessionStatus::Absent)->where('absent_by', $party);
    }

    /** Sessions whose PAID date falls in the window (inclusive). */
    public function scopePaidBetween(Builder $query, string $start, string $end): Builder
    {
        return $query->whereBetween('paid_date', [$start, $end]);
    }

    public function scopeForInstructor(Builder $query, int $instructorId): Builder
    {
        return $query->where('instructor_id', $instructorId);
    }

    /** Classes taught ahead of their scheduled slot. */
    public function scopeEarly(Builder $query): Builder
    {
        return $query->whereNotNull('held_date');
    }

    public function scopeUnmarked(Builder $query): Builder
    {
        return $query->whereNull('status');
    }

    /**
     * Makeups still owed on a day later than $date, in either shape.
     *
     * A makeup is a class the student has already agreed to come back for, so it
     * has one of their prepaid sessions spoken for. Both shapes count — see
     * MAKEUP_MARKER: the current one points forward from the postponed row, the
     * legacy one is an unmarked row sitting on the day it lands.
     *
     * Only makeups AFTER $date. One that has already come and gone unmarked is
     * its own problem, and letting it go on cancelling out the student's
     * timetable would hide live classes for as long as the row survives.
     */
    public function scopeMakeupOwedAfter(Builder $query, string $date): Builder
    {
        return $query->where(fn (Builder $q) => $q
            ->where(fn (Builder $current) => $current
                ->where('status', SessionStatus::Postponed)
                ->whereNotNull('rescheduled_date')
                ->where('rescheduled_date', '>', $date))
            ->orWhere(fn (Builder $legacy) => $legacy
                ->whereNull('status')
                ->where('postpone_reason', 'like', self::MAKEUP_MARKER.'%')
                ->where('scheduled_date', '>', $date)));
    }

    // ------------------------------------------------------------------ helpers

    public function isEarly(): bool
    {
        return $this->held_date !== null;
    }

    /**
     * The date this row is a makeup for, when the makeup itself IS this row.
     *
     * Legacy shape only — see MAKEUP_MARKER. Null for a postponed original in
     * the current shape: that row is the class being moved, not the makeup, and
     * points forward via `rescheduled_date` instead.
     */
    public function makeupOrigin(): ?CarbonImmutable
    {
        $reason = (string) $this->postpone_reason;

        if (! str_starts_with($reason, self::MAKEUP_MARKER)) {
            return null;
        }

        try {
            return CarbonImmutable::parse(trim(substr($reason, strlen(self::MAKEUP_MARKER))));
        } catch (\Throwable) {
            // Free text an instructor typed that happens to start the same way.
            return null;
        }
    }

    /**
     * When this class starts.
     *
     * A makeup keeps its own agreed hour: it lands on whatever day the student
     * can come back, which is often a weekday they have no timetable slot on at
     * all, so `scheduled_time` is empty and `makeup_time` holds the real time.
     */
    public function startTime(): ?string
    {
        return $this->scheduled_time ?: $this->makeup_time;
    }

    public function isSettled(): bool
    {
        return in_array($this->status?->value, SessionStatus::payableValues(), true);
    }

    /**
     * Whether this session pays the instructor.
     *
     * Present pays. Student-absent pays — the instructor showed up and waited.
     * Teacher-absent does not; it is deducted instead. Postponed and unmarked
     * sessions were never taught.
     */
    public function isPayable(): bool
    {
        return $this->status === SessionStatus::Present
            || ($this->status === SessionStatus::Absent && $this->absent_by === Party::Student);
    }

    /** Whether this session is deducted from the instructor's payout. */
    public function isDeductible(): bool
    {
        return $this->status === SessionStatus::Absent && $this->absent_by === Party::Teacher;
    }
}
