<?php

namespace App\Models;

use App\Enums\PayoutStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A weekly payslip, frozen at the moment of payment so that later edits to
 * attendance cannot silently restate what was already paid out.
 */
class Payout extends Model
{
    use HasFactory;

    protected $fillable = [
        'instructor_id',
        'week_start',
        'week_end',
        'gross_earnings',
        'deductions',
        'audio_earnings',
        'video_kids_earnings',
        'video_adults_earnings',
        'sessions_paid',
        'sessions_deducted',
        'status',
        'paid_at',
        'paid_by',
        'notes',
    ];

    /** net_earnings is generated by the database. */
    protected $guarded = ['id', 'net_earnings'];

    protected $casts = [
        'week_start' => 'date',
        'week_end' => 'date',
        'gross_earnings' => 'decimal:2',
        'deductions' => 'decimal:2',
        'net_earnings' => 'decimal:2',
        'audio_earnings' => 'decimal:2',
        'video_kids_earnings' => 'decimal:2',
        'video_adults_earnings' => 'decimal:2',
        'sessions_paid' => 'integer',
        'sessions_deducted' => 'integer',
        'status' => PayoutStatus::class,
        'paid_at' => 'datetime',
    ];

    public function instructor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'instructor_id');
    }

    public function paidBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'paid_by');
    }

    public function scopePaid(Builder $query): Builder
    {
        return $query->where('status', PayoutStatus::Paid);
    }

    public function scopePending(Builder $query): Builder
    {
        return $query->where('status', PayoutStatus::Pending);
    }

    public function weekLabel(): string
    {
        return $this->week_start->format('M j').' – '.$this->week_end->format('M j, Y');
    }
}
